require('dotenv').config();

const DB_URL = process.env.DB_URL;

// Richiedo modulo mongoose e schema persona
var mongoose = require('mongoose');
mongoose.Promise = global.Promise;
var Persona = require('./persona.js');

// Connessione al DB su mLab
mongoose.connect(DB_URL, {useMongoClient: true});
const db = mongoose.connection;
db.on('error', err => {
  console.error(`Error while connecting to DB: ${err.message}`);
});
db.once('open', () => {
  console.log('DB connected successfully!');
});

const allCourse = require('./allCourse');

test('check ricerca tutti i ruoli | Ruoli', () => {
    var azioni = [];
    azioni[0] = '';

    var corso1 = "Mobile and satellite communications";
    var corso2 = "Propagazione elettromagnetica";
    var corso3 = "Data mining";
    var corso4 = "Informatica";
    var corso5 = "Machine Learning";
    var corso6 = "Imaging and diagnostic techniques";
    var corso7 = "Inverse problems and optimization";
    var corso8 = "Radar and 5G architectures and systems";
    var corso9 = "Radar architectures and systems";
    var corso10 = "Basi di dati";
    var corso11 = "Big data and social networks";
    var corso12 = "Data mining";
    var corso13 = "Research project";
    var corso14 = "Laboratorio di programmazione per sistemi mobili e tablet";
    var corso15 = "Language Understanding System";
    var corso16 = "Programmazione 1";
    var corso17 = "Formal methods";
    var corso18 = "Programmazione 1";
    var corso19 = "Project course";
    var corso20 = "Research project";
    var corso21 = "Affective computing";
    var corso22 = "Informatica";
    var corso23 = "Intelligent Optimization for data science";
    var corso24 = "Research project";
    var corso25 = "Science, technology and business";
    var corso26 = "Computational linguistics";
    var corso27 = "Text processing";
    var corso28 = "Bioinformatics";
    var corso29 = "Data mining";
    var corso30 = "Laboratory of biological data mining";
    var corso31 = "Programmazione ad oggetti";
    var corso32 = "Data hiding";
    var corso33 = "Multimedia Data Security";
    var corso34 = "Probabilità e statistica per l'ingegneria dell'informazione";
    var corso35 = "Informatica e rappresentazione della conoscenza";
    var corso36 = "Informatica ed elementi di programmazione 1";
    var corso37 = "Sistemi informativi";
    var corso38 = "Algoritmi avanzati";
    var corso39 = "Machine learning for data science";
    var corso40 = "Reti avanzate";
    var corso41 = "Reti avanzate e sicurezza";
    var corso42 = "Sicurezza dei dati";
    var corso43 = "Ingegneria del software 2";
    var corso44 = "Advanced remote sensing systems";
    var corso45 = "Comunicazioni elettriche";
    var corso46 = "Fondamenti di comunicazioni digitali";
    var corso47 = "Radar and radiolocalization";
    var corso48 = "Sistemi di telerilevamento";
    var corso49 = "Computer vision";
    var corso50 = "Computer vision and multimedia analysis";
    var corso51 = "Computer vision and multimedia analysis";
    var corso52 = "Comunicazioni multimediali";
    var corso53 = "Project course";
    var corso54 = "Project course on media retrieval";
    var corso55 = "Project course on computer graphics";
    var corso56 = "Fondamenti di sistemi operativi";
    var corso57 = "Network security";
    var corso58 = "Research Project";
    var corso59 = "Sistemi operativi 1";
    var corso60 = "Design experience";
    var corso61 = "Laboratorio di ricerca su sistemi informativi";
    var corso62 = "Participatory design";
    var corso63 = "Privacy and Intellectual Property Rights";
    var corso64 = "Sistemi informativi (a sociologia)";
    var corso65 = "Design experience";
    var corso66 = "Interazione Uomo - Macchina";
    var corso67 = "Research Project";
    var corso68 = "User experience / HCI";
    var corso69 = "User-centered design";
    var corso70 = "Comunicazioni elettriche";
    var corso71 = "Comunicazioni multimediali";
    var corso72 = "Elaborazione e trasmissione delle immagini";
    var corso73 = "Algoritmi e tecniche di ottimizzazione";
    var corso74 = "Wired communications systems and devices";
    var corso75 = "Agent-oriented software engineering";
    var corso76 = "Gestione dati e business intelligence";
    var corso77 = "Ingegneria del software 1";
    var corso78 = "Knowledge and Data Integration";
    var corso79 = "Knowledge and representation in an open world";
    var corso80 = "Logica";
    var corso81 = "Computability and computational complexity";
    var corso82 = "Linguaggi di programmazione";
    var corso83 = "Programmazione 2";
    var corso84 = "Advanced network modelling and design";
    var corso85 = "Design of networks and communication systems";
    var corso86 = "Network modelling and design";
    var corso87 = "Progettazione di reti e sistemi di comunicazione";
    var corso88 = "Project course on software defined networking";
    var corso89 = "Reti";
    var corso90 = "Laboratory of Nomadic communication";
    var corso91 = "Research Project";
    var corso92 = "Reti";
    var corso93 = "Simulation and performance evaluation";
    var corso94 = "Wireless mesh and vehicular networks";
    var corso95 = "Innovation and Entrepreneurship studies in ICT";
    var corso96 = "Introduction to service design and engineering";
    var corso97 = "Research project";
    var corso98 = "Campi elettromagnetici";
    var corso99 = "Fondamenti di campi elettromagnetici";
    var corso100 = "Industrial trends in communications";
    var corso101 = "Tecniche di diagnostica biomedicale";
    var corso102 = "Cyber Security Risk Assessment";
    var corso103 = "ICT Innovation";
    var corso104 = "ICT Innovation - Product Design and Development";
    var corso105 = "Offensive Technologies";
    var corso106 = "Project course";
    var corso107 = "Research Project";
    var corso108 = "Recognition systems";
    var corso109 = "Trasmissione numerica";
    var corso110 = "Algoritmi e strutture dati";
    var corso111 = "Algoritmi e strutture dati (I UD)";
    var corso112 = "Algoritmi e strutture dati (II UD)";
    var corso113 = "Fondamenti di algoritmi e strutture dati";
    var corso114 = "Project course";
    var corso115 = "Research Project";
    var corso116 = "Scientific Programming";
    var corso117 = "Advanced Natural Language Processing and Information Retrieval";
    var corso118 = "Introduzione alla programmazione per il web";
    var corso119 = "Project course";
    var corso120 = "Architettura degli elaboratori";
    var corso121 = "Calcolatori";
    var corso122 = "Fondamenta di Architetture digitali";
    var corso123 = "Laboratory of applied of robotics";
    var corso124 = "Real time operating system and middleware";
    var corso125 = "Research Project";
    var corso126 = "Teoria dei sistemi";
    var corso127 = "Advanced computing architectures";
    var corso128 = "Elettronica";
    var corso129 = "Fondamenti di elettronica";
    var corso130 = "Reti logiche (modulo 1)";
    var corso131 = "Reti logiche (modulo 2)";
    var corso132 = "Distributed system 1";
    var corso133 = "Laboratory of wireless sensor networks";
    var corso134 = "Linguaggi di programmazione";
    var corso135 = "Concurrency";
    var corso136 = "Linguaggi formali e compilatori";
    var corso137 = "E-learning";
    var corso138 = "Laboratorio di programmazione per sistemi mobili e tablet";
    var corso139 = "Linguaggi di programmazione";
    var corso140 = "Research project";
    var corso141 = "Web architecture";
    var corso142 = "Communication systems";
    var corso143 = "Design of networks and communication systems";
    var corso144 = "Progettazione di reti e sistemi di comunicazione";
    var corso145 = "Teoria dei segnali";


    return allCourse('html').then( (aiTxt) => {
        expect(aiTxt).toContain(corso1);
        expect(aiTxt).toContain(corso2);
        expect(aiTxt).toContain(corso3);
        expect(aiTxt).toContain(corso4);
        expect(aiTxt).toContain(corso5);
        expect(aiTxt).toContain(corso6);
        expect(aiTxt).toContain(corso7);
        expect(aiTxt).toContain(corso8);
        expect(aiTxt).toContain(corso9);
        expect(aiTxt).toContain(corso10);
        expect(aiTxt).toContain(corso11);
        expect(aiTxt).toContain(corso12);
        expect(aiTxt).toContain(corso13);
        expect(aiTxt).toContain(corso14);
        expect(aiTxt).toContain(corso15);
        expect(aiTxt).toContain(corso16);
        expect(aiTxt).toContain(corso17);
        expect(aiTxt).toContain(corso18);
        expect(aiTxt).toContain(corso19);
        expect(aiTxt).toContain(corso20);
        expect(aiTxt).toContain(corso21);
        expect(aiTxt).toContain(corso22);
        expect(aiTxt).toContain(corso23);
        expect(aiTxt).toContain(corso24);
        expect(aiTxt).toContain(corso25);
        expect(aiTxt).toContain(corso26);
        expect(aiTxt).toContain(corso27);
        expect(aiTxt).toContain(corso28);
        expect(aiTxt).toContain(corso29);
        expect(aiTxt).toContain(corso30);
        expect(aiTxt).toContain(corso31);
        expect(aiTxt).toContain(corso32);
        expect(aiTxt).toContain(corso33);
        expect(aiTxt).toContain(corso34);
        expect(aiTxt).toContain(corso35);
        expect(aiTxt).toContain(corso36);
        expect(aiTxt).toContain(corso37);
        expect(aiTxt).toContain(corso38);
        expect(aiTxt).toContain(corso39);
        expect(aiTxt).toContain(corso40);
        expect(aiTxt).toContain(corso41);
        expect(aiTxt).toContain(corso42);
        expect(aiTxt).toContain(corso43);
        expect(aiTxt).toContain(corso44);
        expect(aiTxt).toContain(corso45);
        expect(aiTxt).toContain(corso46);
        expect(aiTxt).toContain(corso47);
        expect(aiTxt).toContain(corso48);
        expect(aiTxt).toContain(corso49);
        expect(aiTxt).toContain(corso50);
        expect(aiTxt).toContain(corso51);
        expect(aiTxt).toContain(corso52);
        expect(aiTxt).toContain(corso53);
        expect(aiTxt).toContain(corso54);
        expect(aiTxt).toContain(corso55);
        expect(aiTxt).toContain(corso56);
        expect(aiTxt).toContain(corso57);
        expect(aiTxt).toContain(corso58);
        expect(aiTxt).toContain(corso59);
        expect(aiTxt).toContain(corso60);
        expect(aiTxt).toContain(corso61);
        expect(aiTxt).toContain(corso62);
        expect(aiTxt).toContain(corso63);
        expect(aiTxt).toContain(corso64);
        expect(aiTxt).toContain(corso65);
        expect(aiTxt).toContain(corso66);
        expect(aiTxt).toContain(corso67);
        expect(aiTxt).toContain(corso68);
        expect(aiTxt).toContain(corso69);
        expect(aiTxt).toContain(corso70);
        expect(aiTxt).toContain(corso71);
        expect(aiTxt).toContain(corso72);
        expect(aiTxt).toContain(corso73);
        expect(aiTxt).toContain(corso74);
        expect(aiTxt).toContain(corso75);
        expect(aiTxt).toContain(corso76);
        expect(aiTxt).toContain(corso77);
        expect(aiTxt).toContain(corso78);
        expect(aiTxt).toContain(corso79);
        expect(aiTxt).toContain(corso80);
        expect(aiTxt).toContain(corso81);
        expect(aiTxt).toContain(corso82);
        expect(aiTxt).toContain(corso83);
        expect(aiTxt).toContain(corso84);
        expect(aiTxt).toContain(corso85);
        expect(aiTxt).toContain(corso86);
        expect(aiTxt).toContain(corso87);
        expect(aiTxt).toContain(corso88);
        expect(aiTxt).toContain(corso89);
        expect(aiTxt).toContain(corso90);
        expect(aiTxt).toContain(corso91);
        expect(aiTxt).toContain(corso92);
        expect(aiTxt).toContain(corso93);
        expect(aiTxt).toContain(corso94);
        expect(aiTxt).toContain(corso95);
        expect(aiTxt).toContain(corso96);
        expect(aiTxt).toContain(corso97);
        expect(aiTxt).toContain(corso98);
        expect(aiTxt).toContain(corso99);
        expect(aiTxt).toContain(corso100);
        expect(aiTxt).toContain(corso101);
        expect(aiTxt).toContain(corso102);
        expect(aiTxt).toContain(corso103);
        expect(aiTxt).toContain(corso104);
        expect(aiTxt).toContain(corso105);
        expect(aiTxt).toContain(corso106);
        expect(aiTxt).toContain(corso107);
        expect(aiTxt).toContain(corso108);
        expect(aiTxt).toContain(corso109);
        expect(aiTxt).toContain(corso110);
        expect(aiTxt).toContain(corso111);
        expect(aiTxt).toContain(corso112);
        expect(aiTxt).toContain(corso113);
        expect(aiTxt).toContain(corso114);
        expect(aiTxt).toContain(corso115);
        expect(aiTxt).toContain(corso116);
        expect(aiTxt).toContain(corso117);
        expect(aiTxt).toContain(corso118);
        expect(aiTxt).toContain(corso119);
        expect(aiTxt).toContain(corso120);
        expect(aiTxt).toContain(corso121);
        expect(aiTxt).toContain(corso122);
        expect(aiTxt).toContain(corso123);
        expect(aiTxt).toContain(corso124);
        expect(aiTxt).toContain(corso125);
        expect(aiTxt).toContain(corso126);
        expect(aiTxt).toContain(corso127);
        expect(aiTxt).toContain(corso128);
        expect(aiTxt).toContain(corso129);
        expect(aiTxt).toContain(corso130);
        expect(aiTxt).toContain(corso131);
        expect(aiTxt).toContain(corso132);
        expect(aiTxt).toContain(corso133);
        expect(aiTxt).toContain(corso134);
        expect(aiTxt).toContain(corso135);
        expect(aiTxt).toContain(corso136);
        expect(aiTxt).toContain(corso137);
        expect(aiTxt).toContain(corso138);
        expect(aiTxt).toContain(corso139);
        expect(aiTxt).toContain(corso140);
        expect(aiTxt).toContain(corso141);
        expect(aiTxt).toContain(corso142);
        expect(aiTxt).toContain(corso143);
        expect(aiTxt).toContain(corso144);
        expect(aiTxt).toContain(corso145);

    })
});

afterAll(() => {
    return mongoose.connection.close();
});
